[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'solmate/=lib/solmate/src/']
gas_reports = ['MockERC721']

# See more config options https://github.com/gakonst/foundry/tree/master/config